"""add final_review column

Revision ID: 3afb6f9dfa8a
Revises: 
Create Date: 2026-04-07 10:28:28.266618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3afb6f9dfa8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit')
    op.drop_table('finding')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finding',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('audit_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('isarp_number', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('section', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('finding_details', mysql.TEXT(), nullable=True),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('due_date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['audit_id'], ['audit.id'], name=op.f('finding_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('audit',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('operator_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audit_year', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('audit_date', sa.DATE(), nullable=True),
    sa.Column('expiry_date', sa.DATE(), nullable=True),
    sa.Column('auditor_name', mysql.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['operator.id'], name=op.f('audit_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
